name: Format docs on PR with Prettier

on:
  # https://stackoverflow.com/a/58740879
  pull_request_target:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PR_OP_GITHUB_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i -g prettier

      - name: Format code with Prettier
        run: npx prettier -cw .

      - name: Check diff
        id: check-diff
        run: |
          EXIT_CODE=0
          git diff --quiet --exit-code || EXIT_CODE=$?
          if [ EXIT_CODE -eq 1 ]; then
            echo "has_diff=true" >> $GITHUB_OUTPUT
          else
            echo "has_diff=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-diff.outputs.has_diff == 'true'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "style: format code with prettier [skip ci]"
          git push "https://x-access-token:${{ secrets.PR_OP_GITHUB_TOKEN }}@github.com/${{ github.event.pull_request.head.repo.full_name }}.git" HEAD:${{ github.event.pull_request.head.ref }}
